### ISSUE TITLE
support v2 of dashboard

### ISSUE THREAD

**Issue by freekmurze** [owenvoke/laravel-dashboard-cloudflare-stats-tile#2]
Hi, 

we've released v2 our dashboard. The only change are the updated requirements: we now require Laravel v8 and Livewire v2.

Could you please tag a new release of your tile?

In most cases these are the things you need to do:
- update the requirement in the composer.json of your tile to `spatie/laravel-dashboard": "^2.0`
- tag a new release. Personally, I would opt for a major release, so you can still do bug fixes on the v1 of your tile.

Thanks!

**Comment by ahosker** [comment]
Have created PR #3

**Comment by owenvoke** [comment]
Released `v2.0.0` with support for this. 👍🏻 Thanks @ahosker!
